package com.example.compose

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF914d00)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffdcc0)
val md_theme_light_onPrimaryContainer = Color(0xFF2f1500)
val md_theme_light_secondary = Color(0xFF745944)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffdcc1)
val md_theme_light_onSecondaryContainer = Color(0xFF2a1707)
val md_theme_light_tertiary = Color(0xFF5c6237)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFe1e7b1)
val md_theme_light_onTertiaryContainer = Color(0xFF191e00)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF201a17)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF201a17)
val md_theme_light_surfaceVariant = Color(0xFFf3dfd2)
val md_theme_light_onSurfaceVariant = Color(0xFF51443a)
val md_theme_light_outline = Color(0xFF847469)
val md_theme_light_inverseOnSurface = Color(0xFFfaeee7)
val md_theme_light_inverseSurface = Color(0xFF352f2b)
val md_theme_light_inversePrimary = Color(0xFFffb779)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFffb779)
val md_theme_dark_onPrimary = Color(0xFF4d2600)
val md_theme_dark_primaryContainer = Color(0xFF6f3900)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdcc0)
val md_theme_dark_secondary = Color(0xFFe3c0a6)
val md_theme_dark_onSecondary = Color(0xFF422c1a)
val md_theme_dark_secondaryContainer = Color(0xFF5a422e)
val md_theme_dark_onSecondaryContainer = Color(0xFFffdcc1)
val md_theme_dark_tertiary = Color(0xFFc5cb97)
val md_theme_dark_onTertiary = Color(0xFF2e330d)
val md_theme_dark_tertiaryContainer = Color(0xFF444a21)
val md_theme_dark_onTertiaryContainer = Color(0xFFe1e7b1)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF201a17)
val md_theme_dark_onBackground = Color(0xFFebe0d9)
val md_theme_dark_surface = Color(0xFF201a17)
val md_theme_dark_onSurface = Color(0xFFebe0d9)
val md_theme_dark_surfaceVariant = Color(0xFF51443a)
val md_theme_dark_onSurfaceVariant = Color(0xFFd6c3b6)
val md_theme_dark_outline = Color(0xFF9f8e82)
val md_theme_dark_inverseOnSurface = Color(0xFF201a17)
val md_theme_dark_inverseSurface = Color(0xFFebe0d9)
val md_theme_dark_inversePrimary = Color(0xFF914d00)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF605751)
val error = Color(0xFFba1b1b)